### PR TITLE
Allow user to create their own mongo config file

### PR DESCRIPTION
**Pull request by juliangrigera**
Addressing issue #8 
Add support for loading .mongodb.conf file so users can override properties like
dbpath and logpath. Make bindIp a variable that can also be overridden from the file too.
Add a simple yaml parsing to find relevant keys. A YAML framework should be better,
but attempted to keep things simple for now.

### CODE REVIEW

**Comment by gcollazo** [comment]
@juliangrigera thanks a lot for contributing.

Instead of parsing the config file we should do something simpler like just passing the [`mongod.conf`](https://docs.mongodb.com/manual/reference/configuration-options/) directly like this: `mongod --config ~/.mongod.conf`. That way we don't have to parse YAML and we can enable all MongoDB configurations.

Thoughts?

**Comment by juliangrigera** [comment]
Hey @gcollazo, thanks for the feedback (and for the App of course)!

I agree, just passing the file would be both cleaner and simpler. But if we avoided the fixed command line args altogether when file is there, some features ("Open logs directory", or the `createDirectories()` function) wouldn't work.

On the other hand, leaving those command line arguments overrides the file's settings. That's why I ended up parsing the .conf: **1st**, for avoiding the command line arguments from taking precedence, and **2nd**, by re-assigning the AppDelegate's variables, the rest of the App's features (e.g. "Open logs directory") are coherent with the paths being effectively used by `mongod`.

Would you consider passing also the `--config ~/.mongod.conf ` argument the when the file's present as an acceptable solution? That way, the rest of the settings on the file would take effect too.

If you find any other solution I'd be willing to implement it of course, just let me know. Thanks!

**Comment by gcollazo** [comment]
I see two possible solutions:

1. If `~/.mongod.conf` is present just pass the `--config ~/.mongod.conf` flag and disable/remove the "open logs directory and createDirectories()" features. This feels like an advanced feature.

1. If you have the time, use a YAML library/framework so we are sure this won't break in the future.

**Comment by juliangrigera** [comment]
I went for option 2 using [behrang/YamlSwift](https://github.com/behrang/YamlSwift). I checked with
- No file / Invalid files (nothing happens, default values are loaded)
- Valid files for overriding fixed settings (i.e. dbPath, logs path, ip - some settings or all 3)
- Valid files with extra settings, other than the 3 named before (e.g. changing default port)
- Mixing the last two cases

Works in all cases, please check and let me know if you want me to change/improve anything. I used Carthage for the framework.

Thanks!

**Comment by juliangrigera** [comment]
Hey @gcollazo, any comments on this?
Any feedback is welcome, thanks!

**Comment by gcollazo** [comment]
@juliangrigera I haven't had the time to test it locally. I will try to make some time this week and get back to you.

**Comment by gcollazo** [comment]
@juliangrigera can you please rebase this PR?

**Pull request closed without merging**
