### PR TITLE
Mongo 5 upgrade

### PR DESCRIPTION
**Pull request by StefanoDeVuono**
Hi @gcollazo et al,

I made some changes to allow an upgrade to Mongo 5.

### Overview:
- [update sparkle](https://github.com/gcollazo/mongodbapp/pull/26/commits/f8096d3aa58036fec95e63327b9b3ba7bb235d43): I updated Sparkle to version 2 (without changing from the deprecated `SUUpdater` class)
- [convert to swift 5](https://github.com/gcollazo/mongodbapp/pull/26/commits/f58a557418357d1c28762ccf8fe8d5d4e9ff712b): I made a small update to Swift 5 syntax
- [upgrade to mongo 5](https://github.com/gcollazo/mongodbapp/pull/26/commits/9e1d73375aae511e7e599256b44d4b75a247ea8a): Finally I updated the `Info.plist` and `update.sh` files.

### Details:
- [update sparkle](https://github.com/gcollazo/mongodbapp/pull/26/commits/f8096d3aa58036fec95e63327b9b3ba7bb235d43): Sparkle is deprecating the `SUUpdater` class and switching to a new system of deltas. However the current class and system of deltas from Sparkle 1.18 is still supported for now.
  - I updated the build target to from 10.9 to 10.11 to support the new version of Sparkle.
- [convert to swift 5](https://github.com/gcollazo/mongodbapp/pull/26/commits/f58a557418357d1c28762ccf8fe8d5d4e9ff712b): The Swift syntax change was very small.
- [upgrade to mongo 5](https://github.com/gcollazo/mongodbapp/pull/26/commits/9e1d73375aae511e7e599256b44d4b75a247ea8a): The `update.sh` was changed as mongo's download page has changed slightly. Feel free to test the curl command used to find the most recent version:
    ```bash
    curl -Ls https://www.mongodb.com/download-center/community | \
       grep -o ',[^,]*"current":true,' | \
       head -n 1 | \
       grep -o '[0-9]*\.[0-9]*\.[0-9]*'
    ``` 
    - The download page format has changed and can no longer be parsed for `option` tags, I parse the versions are stored in JSON, although there are other solutions (I could try parsing the html and there's a `current.json` endpoint mongo provides; however, between parsing HTML, JSON within HTML or a JSON endpoint and without being able to guarantee that a user has `jq` installed, it feels like there's no great solution.)
    - Also, note that as of Mongo Server 5.0.7, there appears _only_ to be a MacOS x86_64 binary, but the download page shows the version 6 release candidate (6.0.0-rc1) has an Apple Silicon build at https://fastdl.mongodb.org/osx/mongodb-macos-arm64-6.0.0-rc1.tgz.

### CODE REVIEW

**Comment by gcollazo** [comment]
@StefanoDeVuono this looks good but I will have to build it and test it further before merging.

Regarding the sparkle update, I would like to have a way to verify that the bundled version matches what can be downloaded from the sparkle website. A checksum verification or something. The thing is that manually verifying all those files is not practical and I wouldn't feel comfortable shipping a new version of the app without some sort of verification of all that.

Do you have any suggestion on how to verify the bundled sparkle with what's on the official website? Maybe another shell script that runs before the build?

**Comment by StefanoDeVuono** [comment]
> Do you have any suggestion on how to verify the bundled sparkle with what's on the official website? Maybe another shell script that runs before the build?

I pushed up some commits that:
- [revert the sparkle update](https://github.com/gcollazo/mongodbapp/pull/26/commits/19c0dcd87d73f24a58ad2037ab756162fae864e5)
- [remove sparkle](https://github.com/gcollazo/mongodbapp/pull/26/commits/701179cef6eac188459d9fc29a3c9f9fbabd0b6c)
- [re-add sparkle as a swift package](https://github.com/gcollazo/mongodbapp/pull/26/commits/9a8230f682f6f1319adab4b646ba9cdabc999161)

Does that seem ok?

_Edit_: apparently, it's not building archives correctly. I'll try to fix this.

**Comment by StefanoDeVuono** [comment]
@gcollazo 

OK. I rebased and squashed some commits for readability.
- [convert to swift 5](https://github.com/gcollazo/mongodbapp/pull/26/commits/56f0ec3067ec4c624263f940ff19286c2e93cdef)
- [upgrade to mongo 5](https://github.com/gcollazo/mongodbapp/pull/26/commits/001925834c849d4689b372be9aaa2c0e6b15a125)
- [delete sparkle framework, add sparkle as swift package (also: cleanup references to frameworks in project file, import sparkle, and delete scheme and remove bridging file)](https://github.com/gcollazo/mongodbapp/pull/26/commits/bed2d58ccdb97ed182a009dc0b94fa17bf3b92d5)

It seems to build. I'm not at all familiar with XCode's build system and it looks like there might be some trickery with Sparkle's signing, but things _appear_ to work.

**Comment by gcollazo** [comment]
@StefanoDeVuono I will give it a spin and report back, thanks for the contribution

**Comment by StefanoDeVuono** [comment]
@gcollazo Have you had a chance to try it out?

**Comment by gcollazo** [comment]
@StefanoDeVuono I got it to build build but is crashing before launching. I'm currently working on other project so I won't have time to try to fix it soon. If you get it to run let me know and I can take a look again.

**Comment by StefanoDeVuono** [comment]
I got the build working but it's mongo 6. Created a new branch for this

**Pull request closed without merging**
